### ISSUE TITLE
"Replace a character of your choice to another"

### ISSUE THREAD

**Issue by cxd4** [ExtremeDude2/Character-Replacer#1]
I tried to do that with your repository.  The only file it has is the `LICENSE` file, and it won't let me. :(

**Comment by ExtremeDude2** [comment]
lol, I didn't even remember making a repo for this. I was going to try and write a program, but forgot about it.

**Comment by cxd4** [comment]
```c
extern int a_program(void);

int main(void)
{
    return a_program();
}
```

Issue solved.
